version: '3.7'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBUSERPW}
      POSTGRES_DB: ${DBNAME}
    env_file:
      - .env
    expose:
      - ${POSTPORT}
    ports:
      - ${POSTPORT}:${POSTPORT}
    restart: unless-stopped

  backend:
    image: backend
    depends_on:
      - postgres
    ports:
      - ${BACKPORT}:${BACKPORT}
    build:
      context: .
      dockerfile: ./src/docker/backend.Dockerfile
  
  frontend:
    image: frontend
    depends_on:
      - postgres
      - backend
    ports:
      - ${FRONTPORT}:${FRONTPORT}
    build:
      context: .
      dockerfile: ./src/docker/frontend.Dockerfile

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PW}
    depends_on:
      - postgres
    ports:
      - ${PGPORT1}:${PGPORT2}
    env_file:
      - .env
    restart: unless-stopped